-- ════════════════════════════════════════════════════════════════════
-- update_and_augment.sql
--
-- Run this once in the Supabase SQL Editor before retraining.
-- Does two things:
--   Part 1 — Fix tc_forecasts so a new forecast always overwrites the
--             old one for the same (depot, target_week).
--   Part 2 — Extend tc_demand_panel from 2022-12-05 to today with
--             augmented demand that reflects Sri Lanka's post-crisis
--             recovery, correct seasonal patterns, and per-week noise.
--
-- After running this SQL:
--   python pipeline.py --mode update   ← backfills weather/econ columns
--   python pipeline.py --mode train    ← retrains the 6 horizon models
-- ════════════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════════════
-- PART 1: Fix tc_forecasts unique constraint
-- ════════════════════════════════════════════════════════════════════
-- Old constraint: UNIQUE (depot_id, as_of_date, horizon_weeks)
--   → same forecast_week can accumulate multiple rows as as_of_date changes
-- New constraint: UNIQUE (depot_id, forecast_week)
--   → re-running forecast for a depot always overwrites the target week row


-- Step 1a: Keep only the latest forecast per (depot_id, forecast_week)
-- Removes stale rows before we can add the new constraint
DELETE FROM tc_forecasts
WHERE id IN (
    SELECT f.id
    FROM tc_forecasts f
    WHERE f.generated_at < (
        SELECT MAX(f2.generated_at)
        FROM tc_forecasts f2
        WHERE f2.depot_id     = f.depot_id
          AND f2.forecast_week = f.forecast_week
    )
);

-- Step 1b: Drop old constraint (name is auto-generated by Postgres)
ALTER TABLE tc_forecasts
    DROP CONSTRAINT IF EXISTS tc_forecasts_depot_id_as_of_date_horizon_weeks_key;

-- Step 1c: Add new constraint
ALTER TABLE tc_forecasts
    ADD CONSTRAINT tc_forecasts_depot_id_forecast_week_key
    UNIQUE (depot_id, forecast_week);


-- ════════════════════════════════════════════════════════════════════
-- PART 2: Augment tc_demand_panel 2022-12-05 → today
-- ════════════════════════════════════════════════════════════════════
--
-- Demand model:
--   demand = pre_crisis_baseline × recovery_factor × seasonal_mult
--            × event_mult × noise
--
-- pre_crisis_baseline = depot average Aug–Nov 2022 ÷ 0.72
--   (0.72 is the crisis multiplier applied during the original pipeline)
--
-- recovery_factor: linear ramp back to pre-crisis over 3 years
--   Dec 2022 = 0.72  →  end 2023 = 0.84  →  end 2024 = 0.95
--   end 2025 = 1.00  →  2026+ = 1.00–1.03
--
-- seasonal_mult: month-level construction demand pattern for Sri Lanka
--   SW monsoon Jun–Sep    ×0.83  (rain suppresses construction)
--   NE monsoon Nov–Jan    ×0.93
--   Dry season Feb–Mar    ×1.15  (peak construction)
--   April Sinhala NY      ×1.18
--   Monsoon onset May≥15  ×0.92
--   Late dry May<15       ×1.05
--
-- event_mult: event overlays on top of seasonal
--   Year-end quarter (Mar ≥ 10)     ×1.10
--   Christmas week (Dec 22–28)      ×0.88
--   Vesak week (May 7–14 approx)    ×0.90
--
-- noise: uniform ±8% → (0.92 + random() * 0.16)
--
-- ON CONFLICT: overwrites augmented rows, never touches data_source='actual'
-- ════════════════════════════════════════════════════════════════════

WITH

depot_baselines AS (
    -- Pre-crisis baseline = crisis-period average / crisis multiplier (0.72)
    SELECT
        depot_id,
        AVG(demand_tonnes) / 0.72 AS pre_crisis_baseline
    FROM tc_demand_panel
    WHERE week_start >= '2022-08-01'
      AND week_start <= '2022-11-28'
      AND demand_tonnes IS NOT NULL
    GROUP BY depot_id
),

missing_weeks AS (
    -- Every Monday from the first missing week to this week
    SELECT gs::date AS week_start
    FROM generate_series(
        '2022-12-05'::date,
        DATE_TRUNC('week', CURRENT_DATE)::date,
        INTERVAL '1 week'
    ) gs
),

new_pairs AS (
    -- depot × week combinations that are not yet marked as actual
    SELECT d.depot_id, w.week_start
    FROM tc_depots d
    CROSS JOIN missing_weeks w
    WHERE NOT EXISTS (
        SELECT 1
        FROM tc_demand_panel p
        WHERE p.depot_id    = d.depot_id
          AND p.week_start  = w.week_start
          AND p.data_source = 'actual'
    )
),

recovery AS (
    -- Smooth linear ramp: crisis level (0.72) → fully recovered (1.00) by end 2025
    -- then modest +3% growth into 2026
    SELECT
        week_start,
        CASE
            WHEN week_start < '2023-01-01' THEN
                0.72

            WHEN week_start < '2024-01-01' THEN
                -- 0.72 → 0.84 over calendar year 2023
                0.72 + 0.12
                    * (week_start - '2022-12-05'::date)::float
                    / ('2023-12-31'::date - '2022-12-05'::date)::float

            WHEN week_start < '2025-01-01' THEN
                -- 0.84 → 0.95 over calendar year 2024
                0.84 + 0.11
                    * (week_start - '2024-01-01'::date)::float
                    / 365.0

            WHEN week_start < '2026-01-01' THEN
                -- 0.95 → 1.00 over calendar year 2025
                0.95 + 0.05
                    * (week_start - '2025-01-01'::date)::float
                    / 365.0

            ELSE
                -- 2026+: gradual growth capped at +3%
                1.00 + 0.03 * LEAST(
                    (week_start - '2026-01-01'::date)::float / 365.0,
                    1.0
                )
        END AS recovery_factor
    FROM missing_weeks
),

seasonal AS (
    SELECT
        week_start,

        -- Monthly construction demand pattern
        CASE
            WHEN EXTRACT(MONTH FROM week_start) BETWEEN 6 AND 9 THEN 0.83
            WHEN EXTRACT(MONTH FROM week_start) = 5
                 AND EXTRACT(DAY FROM week_start) >= 15              THEN 0.92
            WHEN EXTRACT(MONTH FROM week_start) = 10                THEN 0.96
            WHEN EXTRACT(MONTH FROM week_start) IN (11, 12)         THEN 0.93
            WHEN EXTRACT(MONTH FROM week_start) = 1                 THEN 0.94
            WHEN EXTRACT(MONTH FROM week_start) IN (2, 3)           THEN 1.15
            WHEN EXTRACT(MONTH FROM week_start) = 4                 THEN 1.18
            WHEN EXTRACT(MONTH FROM week_start) = 5
                 AND EXTRACT(DAY FROM week_start) < 15              THEN 1.05
            ELSE 1.0
        END AS seasonal_mult,

        -- Event overlays
        CASE
            WHEN EXTRACT(MONTH FROM week_start) = 3
                 AND EXTRACT(DAY FROM week_start) >= 10             THEN 1.10
            WHEN EXTRACT(MONTH FROM week_start) = 12
                 AND EXTRACT(DAY FROM week_start) BETWEEN 22 AND 28 THEN 0.88
            WHEN EXTRACT(MONTH FROM week_start) = 5
                 AND EXTRACT(DAY FROM week_start) BETWEEN 7 AND 14  THEN 0.90
            ELSE 1.0
        END AS event_mult

    FROM missing_weeks
)

INSERT INTO tc_demand_panel (
    depot_id,
    week_start,
    demand_tonnes,
    data_source
)
SELECT
    np.depot_id,
    np.week_start,
    GREATEST(
        10.0,
        ROUND(
            (
                db.pre_crisis_baseline
                * r.recovery_factor
                * s.seasonal_mult
                * s.event_mult
                * (0.92 + random() * 0.16)   -- ±8% uniform noise
            )::numeric,
            2
        )
    )                   AS demand_tonnes,
    'augmented'         AS data_source

FROM new_pairs  np
JOIN depot_baselines db ON db.depot_id   = np.depot_id
JOIN recovery        r  ON r.week_start  = np.week_start
JOIN seasonal        s  ON s.week_start  = np.week_start

ON CONFLICT (depot_id, week_start) DO UPDATE SET
    demand_tonnes = CASE
        WHEN tc_demand_panel.data_source = 'actual'
        THEN tc_demand_panel.demand_tonnes      -- never overwrite real data
        ELSE EXCLUDED.demand_tonnes
    END,
    data_source = CASE
        WHEN tc_demand_panel.data_source = 'actual' THEN 'actual'
        ELSE 'augmented'
    END;
